# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# docker build -f examples/xo_go/Dockerfile-installed-xenial -t sawtooth-xo-tp-go .

# -------------=== mdata-tp-go build ===-------------

FROM ubuntu:xenial as mdata-tp-go-builder

ENV VERSION=AUTO_STRICT

RUN echo "deb [arch=amd64] http://repo.sawtooth.me/ubuntu/ci xenial universe" >> /etc/apt/sources.list \
 && echo "deb http://archive.ubuntu.com/ubuntu xenial-backports universe" >> /etc/apt/sources.list \
 && (apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 8AA7AF1F1091A5FD \
 || apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 8AA7AF1F1091A5FD) \
 && apt-get update \
 && apt-get install -y -q --allow-downgrades \
    wget \
    build-essential \
    git \
    libssl-dev \
    libzmq3-dev \
    openssl \
    pkg-config \
    python3-grpcio-tools=1.1.3-1 \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && wget --no-check-certificate https://dl.google.com/go/go1.12.2.linux-amd64.tar.gz \
 && tar -xvf go1.12.2.linux-amd64.tar.gz \
 && mv go /usr/local 

ENV GOROOT=/usr/local/go

ENV GOPATH=/go:/go/src/github.com/hyperledger/sawtooth-sdk-go:/go/src/mdata_go/src/mdata_client:/go/src/mdata_go/src/mdata_processor

ENV PATH=$PATH:/project/bin:/go/bin:$GOROOT/bin

RUN mkdir /go

RUN go get -u \
    google.golang.org/grpc \
    github.com/golang/protobuf/proto \
    github.com/golang/protobuf/protoc-gen-go \
    github.com/pebbe/zmq4 \
    github.com/satori/go.uuid \
    github.com/btcsuite/btcd/btcec \
    github.com/jessevdk/go-flags \
    github.com/pelletier/go-toml \
    github.com/golang/mock/gomock \
    github.com/golang/mock/mockgen \
    github.com/hyperledger/sawtooth-sdk-go \
    golang.org/x/crypto/ssh \
    gopkg.in/yaml.v2 \
    github.com/stretchr/testify/mock \
&& cd /go/src/github.com/hyperledger/sawtooth-sdk-go \
&& go generate 

WORKDIR /go/src/mdata_go

COPY . .

RUN cd /go/src/mdata_go \
 && if [ -d "bin" ]; then rm -rf bin; fi \
 && mkdir bin \
 && echo "+================== BUILDING TRANSACTION PROCESSOR =============================+" \
 && cd /go/src/mdata_go/src/mdata_processor \ 
 && go build -o /go/src/mdata_go/bin/mdata-tp-go \
 && echo "+================== BUILDING CLI CLIENT =============================+" \
 && cd /go/src/mdata_go/src/mdata_client \
 && ST_VERSION="0.1.2.dev771" \
 && go build -ldflags "-X main.DISTRIBUTION_VERSION=${ST_VERSION}" -o /go/src/mdata_go/bin/mdata-go

 #&& ST_VERSION=$(/go/src/github.com/hyperledger/sawtooth-sdk-go/bin/get_version) \

RUN pkg=mdata_go \
 && echo "+================== PACKAGING =============================+" \
 && GO_TP_DASH=$(echo $pkg | sed s/_/-/) \
 && CHANGELOG_DIR="debian/usr/share/doc/sawtooth-tp-$GO_TP_DASH" \
 && ST_VERSION="0.1.2.dev771" \
 && cd /go/src/mdata_go \
 && if [ -d "debian" ]; then rm -rf debian; fi \
 && mkdir -p debian/DEBIAN \
 && mkdir -p $CHANGELOG_DIR \
 && cp /go/src/mdata_go/packaging/ubuntu/* debian \
 && sed -i -e"s/@VERSION@/$ST_VERSION/" debian/control \
 && sed -i -e"s/@VERSION@/$ST_VERSION/" debian/changelog \
 && cp debian/changelog $CHANGELOG_DIR \
 && mv debian/changelog $CHANGELOG_DIR/changelog.Debian \
 && gzip --best $CHANGELOG_DIR/changelog \
 && gzip --best $CHANGELOG_DIR/changelog.Debian \
 && mv debian/control debian/DEBIAN \
 && mv debian/postinst debian/DEBIAN \
 && PACKAGENAME=$(awk '/^Package:/ { print $2 }' debian/DEBIAN/control) \
 && PACKAGEVERSION=$(dpkg-parsechangelog -S version -l $CHANGELOG_DIR/changelog.gz) \
 && PACKAGEARCH=$(dpkg-architecture -qDEB_BUILD_ARCH) \
 && mkdir debian/usr/bin \
 && cp -R bin/ debian/usr/ \
 && cp -R packaging/systemd/* debian/ \
 && fakeroot dpkg-deb --build debian \
 && echo -- \
 && echo "${PACKAGENAME}_${PACKAGEVERSION}_${PACKAGEARCH}.deb" \
 && echo -- \
 && mv debian.deb "${PACKAGENAME}_${PACKAGEVERSION}_${PACKAGEARCH}.deb"

# -------------=== sawtooth-mdata-tp-go build ===-------------

FROM ubuntu:xenial

COPY --from=mdata-tp-go-builder /go/src/mdata_go/sawtooth-mdata-tp-go_*.deb /tmp

RUN apt-get update \
 && dpkg -i /tmp/sawtooth-*.deb || true \
 && apt-get -f -y install

CMD ["mdata-tp-go", "-vv"]